<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
$_item = $block->getItem();
$product = $_item->getProduct();
if ($_item->getMediaclipProjectId()) {
    $mediaclipprojectid = $_item->getMediaclipProjectId();
}
/**
 * 2018-06-16 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * Notice: Undefined variable: mediaclipprojectid in 
 * app/design/frontend/Infortis/ultimo/Magento_Checkout/templates/cart/item/renderer/actions/edit.phtml
 * on line 20 
 */
else {
	$mediaclipprojectid = null;
}
$url = null;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());

// check if it is a mediaclip product
if ($product->getAttributeSetId() != 4) {
	if ($mediaclipprojectid) {
		$additional = array('mode' => 'editCartProject', 'projectId' => "$mediaclipprojectid");
		$helper = mc_h();
		$url = $helper->getEditorUrl($product, $additional);
	}
}else{
	$url = $block->getConfigureUrl();
}
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit"
       href="<?= /* @escapeNotVerified */ $url ?>"
       title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
        <span>
            <?= /* @escapeNotVerified */ __('Edit') ?>
        </span>
   </a>
<?php endif ?>
