<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<!-- <script type="text/javascript" src="<?php //echo $block->getViewFileUrl('js/jquery.fancybox.pack.js',['_secure' => true]); ?>"></script> -->
<!-- <link rel="stylesheet" href="<?php //echo $block->getViewFileUrl('css/jquery.fancybox.css',['_secure' => true]);?>" /> -->
<?php $_product = $block->getProduct(); ?>

<?php
	// 2019-09-04 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	// «Port a Shopify / React.js product designer app to Magento 2»:
	// https://www.upwork.com/ab/f/contracts/22344597
	if (!ikf_is_mediaclip_product($_product)): ?>

    <?php $buttonTitle = __('Add to Cart'); ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                    </div>
                </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php else: ?>
        <?php if (!empty($_product->getProductButtonLabel())): ?>
        <?php $buttonTitle = $_product->getProductButtonLabel() ; ?>
        <?php else: ?>
        <?php $buttonTitle = __('/Edit'); ?>
        <?php endif; ?>
        <?php
           //echo "<pre>"; print_r($_product->getProductButtonLabel());
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->create('Magento\Customer\Model\Session');
        ?>
        <?php //if ($customerSession->isLoggedIn()) : ?>
            <!-- <div class="box-tocart">
                <div class="fieldset">
                    <div class="actions">
                        <button type="submit"
                                title="<?php /* @escapeNotVerified */ //echo $buttonTitle ?>"
                                class="action primary tocart"
                                id="product-addtocart-button">
                            <span><?php /* @escapeNotVerified */ //echo $buttonTitle ?></span>
                        </button>
                        <?php //echo $block->getChildHtml('', true) ?>
                    </div>
                </div>
            </div> -->
        <?php //else: ?>
            <div class="box-tocart">
                <div class="fieldset">
                    <div class="actions">
                        <button 
                                type="submit"
                                title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                id = "product-addtocart-button"
                                class="action primary tocart toggleCheckoutModal"
                                >
                            <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                        </button>
                        <?php echo $block->getChildHtml('', true) ?>
                    </div>
                </div>
            </div>
        <?php //endif; ?>
<?php endif; ?>


<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<script type="text/javascript">
/*    require([
  'jquery',
  'jquery/ui'
], function($){
    var script = document.createElement("script");
    script.src = "<?php //echo $block->getViewFileUrl('js/jquery.fancybox.pack.js',['_secure' => true]); ?>";
    script.async = true; //asynchronous
    document.getElementsByTagName("head")[0].appendChild(script);
   jQuery(document).on('click','.toggleCheckoutModal' ,function(e) {
    e.preventDefault();

       console.log('customerLogin');
        
            jQuery('<div id="disablebackground"></div>').prependTo('body');
            customerLoginRegister();
        
    });
    jQuery('.fancybox-close').click(function() {
        jQuery('#disablebackground').remove();
    });
    
});
    function customerLoginRegister() {
        jQuery.fancybox({
            'type' : 'iframe', 
            'closeBtn' : true,
            helpers   : { 
               overlay : {closeClick: false} 
            },
            'href': '/mediacliphub/customer/account',
            afterClose: function() {
                jQuery('#disablebackground').remove();
            },
            beforeLoad: function(){
                console.log('beforeLoad');
                
            },
            afterLoad: function(current, previous) {
               
                console.log('afterLoad');
                jQuery('body').loader('hide');
            }
        });
    }*/
</script>

<style type="text/css">
.fancybox-close {
    
    top: -2px !important;
    right: -2px !important;
}
div#disablebackground {
    background: rgba(0,0,0,0.8);
    width: 100%;
    height: 100%;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    right: 0;
    z-index: 5000;
}
#fancybox-outer{
    background:#fff url("$path to animation/ajax-loader.gif") no-repeat 50% 50% !important;
}
.fancybox-overlay  .fancybox-type-iframe{ height: 456px !important; z-index: 5000; }
.fancybox-overlay  .fancybox-type-iframe .fancybox-inner { height: 100% !important }
.fancybox-overlay  .fancybox-type-iframe .fancybox-inner .fancybox-iframe { height: 100% !important; }
a.fancybox-item.fancybox-close:before {
    content: "X";
    position: absolute;
    right: 24px;
    background: #333;
    color: #fff;
    width: 25px;
    height: 25px;
    border-radius: 100%;
    text-align: center;
    line-height: 27px;
    border: 2px solid #fff;
    box-shadow: -1px 0px 3px rgba(0,0,0,0.8);
    font-weight: bold;
}

.fancybox-close {
    top: -2px !important;
    right: 0px !important;
    position: relative;
    float: right;
    width: 30px;
    height: 30px;
}
</style>
<?php endif; ?>
