<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_FbPixel
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper('Webkul\FbPixel\Helper\Data');
$pixel_id = $helper->getPixelId();
if ($pixel_id & $helper->getConfigValue('purchase')): 
    $orderDetails = $helper->getOrderDetails();
?>
    <script>
        fbq('track', 'Purchase',{
            content_type: 'product',
            content_ids: [<?php echo $orderDetails['product_sku']; ?>],
            value: <?php echo $orderDetails['total']; ?>,
            currency: '<?php echo $orderDetails['currency']; ?>'
        });
    </script>
<?php endif;