<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_FbPixel
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper('Webkul\FbPixel\Helper\Data');
$pixel_id = $helper->getPixelId();

if ($pixel_id & $helper->getConfigValue('product')): ?>
    <script>
        fbq('track', 'ViewContent', {
            content_type: 'product',
            content_name: '<?php echo $block->getProduct()->getName() ?>',
            content_ids: '<?php echo $block->getProduct()->getSku() ?>',
            value: '<?php echo $block->getProduct()->getFinalPrice() ?>',
            currency: '<?php echo $helper->getStore()->getBaseCurrencyCode() ?>'
        });
    </script>
<?php endif; ?>